export const GET_DOGS = 'GET_DOGS';

export const GET_DOG_DETAILS = 'GET_DOG_DETAILS';
export const CLEAR_DOG_DETAILS= 'CLEAR_DOG_DETAILS'

export const POST_DOG = 'POST_DOG';

export const SEARCH_DOG_NAME = 'SEARCH_DOG_NAME';

export const APPLY_FILTERS_AND_ORDER='APPLY_FILTERS_AND_ORDER';

export const GET_TEMPS = 'GET_TEMPS';
